# Generated by Django 4.1 on 2023-11-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_types',
            field=models.CharField(choices=[('USER', 'User'), ('AUTHOR', 'Author')], default='User', max_length=26),
        ),
    ]
