# Generated by Django 4.1 on 2023-11-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'order_date', 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role_types',
            field=models.CharField(choices=[(1, 'USER'), (2, 'AUTHOR')], default='User', max_length=26),
        ),
    ]
