# Generated by Django 4.1 on 2023-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_role_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'role_types', 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role_types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USER'), (2, 'AUTHOR')], default=1),
        ),
    ]
